import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import Sidebar from "@/components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TyrAds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
